### ISSUE TITLE
1.875 size

### ISSUE THREAD

**Issue by eberkain** [linuxgurugamer/NRAP#1]
The MOLE mod adds a set of early game parts that are between the normal 1.25 and 2.5 size,  It would be nice if the NRAP could be scaled to match when the mod is installed. 

http://forum.kerbalspaceprogram.com/index.php?/topic/154893-122-v146-mark-one-laboratory-extensions-mole/&page=3

**Comment by FlyingFalap** [comment]
I'd love to see a fine-grained slider that snaps to the nearest 0.005 lets say. Would give tons of flexibility to size the test weight to simulate different sized payloads or fairings. Edit: I am using Tweakscale, Tantares and BDB as well as some other mods which result in some odd sized stages such as .9375 (close enough to .938), 1.5, 1.875, 3.125, etc. Having a freely adjustable diameter would be great.

**Comment by linuxgurugamer** [comment]
This was added a while ago
