### ISSUE TITLE
Probe control doesn't work with CommNet

### ISSUE THREAD

**Issue by TruePikachu** [linuxgurugamer/NRAP#3]
While the NRAP parts have `ModuleCommand` -> `minimumCrew = 0`, and (for RemoteTech) `ModuleRTAntennaPassive`, they lack `ModuleDataTransmitter`. Without `ModuleDataTransmitter`, the NRAP parts lack any internal antenna, and as such can't be controlled if difficulty settings are set such that a CommNet signal is required for probe control.

As a side note, if you put an NRAP part alone in an editor, you get the following message about the vessel in the engineer's report:
`[+] The vessel has air intakes but no engines to use them.`
`[-] Your unmanned vessel does not have an antenna and will have limited control functionality.`
This is probably a bug in stock, especially considering all the unmanned probe cores have built-in antennas, but confusing nonetheless.

**Comment by TruePikachu** [comment]
Copying the Stayputnik's internal antenna into the NRAP parts allows them to be controlled, but doesn't do anything about that strange message.

**Comment by linuxgurugamer** [comment]
Also needed Kerbnet access, working on it now

**Comment by linuxgurugamer** [comment]
If you want to have a  laugh, put a single tank into the editor and look at the report.  The same odd message will show up.
I'll be reporting this as a bug to Squad.
NRAP will be updated this morning

**Comment by linuxgurugamer** [comment]
Just an update, this bug was reported to Squad 2 months ago here:
https://bugs.kerbalspaceprogram.com/issues/16964?issue_count=4&issue_position=1&next_issue_id=13096

**Comment by linuxgurugamer** [comment]
And updated
