### ISSUE TITLE
Negative cost

### ISSUE THREAD

**Issue by yalov** [linuxgurugamer/NRAP#5]
KSP 1.6.1,  
NRAP 1.5.11.4

![](https://i.imgur.com/uqC2Wq7.png)

Request: 
Dry Cost TextField on the toggled NRAP window.

**Comment by linuxgurugamer** [comment]
I've fixed the part, will release soon.
Drycost is meaningless, it is always the same, 250 for each part

Thank you for the report

**Comment by yalov** [comment]
procedural changeable costs (like mass) for these parts can be helpful for a some kind of KerbalConstructionTime testing, or other mods, that are rely on a vessel's cost

**Comment by linuxgurugamer** [comment]
That may be, but this is a test weight only.  To start figuring out the dry vs wet cost starts becoming more of a hassle than it's worth.  At least to me

**Comment by linuxgurugamer** [comment]
I hate it when someone asks a question like this.  It's been niggling at the back of my mind, so I'm going to take a look.  May be a lot simpler than I thought, looks like the cost is based directly on the weight, if so, I can add that (still not sure why it's needed).

**Comment by linuxgurugamer** [comment]
New update with the costs broken out is now available
