### ISSUE TITLE
Lowest weight is 0.02t, not 0.01t as advertised

### ISSUE THREAD

**Issue by tjanke42** [linuxgurugamer/NRAP#8]
NRAP's forum page says nrap weight range is "0.01 - 1000t", but the lowest it can go is actually 0.02t.  If you try to set the nrap's weight to 0.01 the text "Dry mass (t)" in the nrap window turns red and the weight remains whatever it was.

This might seem really nitpicky, but I'm testing a single stage 0.625 launcher and that 0.01 weight would be really handy right now.  :)

Love nrap, use it all the time; thanks for maintaining it!

**Comment by linuxgurugamer** [comment]
Typo, will get it fixed

For now, use this:  0.01001
Shouldn't affect your tests, I'll see what I can do

**Comment by tjanke42** [comment]
That'll do.  Thanks very much!
